version: '3.8'
services:
  node-app:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres-database
    environment:
      - PORT:${PORT}
    volumes:
      - type: bind
        source: ./src
        target: /home/app/src
      - app_logs:/home/app/logs
    restart: unless-stopped
    networks:
      - rest-network
  postgres-database:
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - rest-network

volumes:
  postgres_data:
  app_logs:

networks:
  rest-network:
    name: rest-network
    driver: bridge
